- name: Delete zabbix dir for sec_installation
  shell: rm -rf {{zabbix_work_dir}}

- name: Clone zabbix in Websoft9 
  git:
    repo: "{{zabbix_git_url}}"
    dest: "{{zabbix_work_dir}}"

- name: Create dir for zabbix
  file: 
    state: directory
    path: "{{item}}"
  loop: 
    - '{{zabbix_work_dir}}/volumes'
    - /data/db/mysql

- name: Rename compose and Run docker-compose 
  shell: |
    sed -i "s/APP_VERSION=.*/APP_VERSION=test/g" .env
    docker-compose up -d
    sleep 30
  args:
    chdir: '{{zabbix_work_dir}}'

- name: Copy the modify login password script 
  copy:
    src: change_login_passwd.sh
    dest: /opt/change_login_passwd.sh
    mode: ugo+x

- name: Set soft link for zabbix
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
  - {src: '{{zabbix_work_dir}}/volumes/var/lib/mysql/',dest: /data/db/mysql}
  - {src: '{{zabbix_work_dir}}/volumes/etc/zabbix/zabbix_agentd.d/',dest: /data/config/zabbix}

# check service and version
- name: Check zabbix service 
  shell: >
    docker ps -a |awk '{print $2,$7}'
  register: check_zabbix_service
  notify: check_zabbix_service
    
- name: Check zabbix version
  shell: |
    sudo echo "zabbix version:" $(docker images |grep zabbix-server |cut -d- -f4) |sudo tee -a /data/logs/install_version.txt  

- name: Check mysql version
  shell: |
    sudo echo "mysql version:" $(docker inspect zabbix-mysql |grep -i mysql_version |cut -d= -f2) |sudo tee -a /data/logs/install_version.txt  
